// Central registry describing every tool on PDF Lovers: its route, copy,
// category, accepted input, configurable options and SEO metadata.
export type FieldType = "text" | "number" | "password" | "select" | "checkbox" | "color" | "textarea";

export type ToolField = {
  key: string;
  label: string;
  type: FieldType;
  placeholder?: string;
  defaultValue?: string | number | boolean;
  options?: Array<{ label: string; value: string }>;
  min?: number;
  max?: number;
  help?: string;
};

export type InputKind =
  | "multi-pdf"
  | "single-pdf"
  | "two-pdf"
  | "images"
  | "docx"
  | "xlsx"
  | "pptx"
  | "html";

export type Category = "Organize" | "Convert" | "Edit & Secure" | "Optimize" | "Utilities";

export type ToolDef = {
  slug: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  category: Category;
  inputKind: InputKind;
  accept: string;
  multiple?: boolean;
  needsPassword?: boolean;
  fields?: ToolField[];
  color: string;
  initials: string;
  actionLabel: string;
  faqs: Array<{ q: string; a: string }>;
};

export const categories: Category[] = ["Organize", "Convert", "Edit & Secure", "Optimize", "Utilities"];

export const tools: ToolDef[] = [
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortDescription: "Combine multiple PDFs into a single document in seconds.",
    longDescription:
      "Upload as many PDF files as you like, drag to reorder them, and merge everything into one clean PDF — all processed locally in your browser.",
    category: "Organize",
    inputKind: "multi-pdf",
    accept: "application/pdf",
    multiple: true,
    color: "from-rose-500 to-orange-400",
    initials: "MG",
    actionLabel: "Merge PDFs",
    faqs: [
      { q: "Is there a limit to how many PDFs I can merge?", a: "No hard limit — merge as many files as your device's memory allows." },
      { q: "Will the page order be preserved?", a: "Yes, pages are combined in the exact order your files are listed." },
    ],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortDescription: "Turn every page into its own PDF, instantly.",
    longDescription: "Split a multi-page PDF into individual single-page PDF files, bundled into one convenient zip download.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-orange-500 to-amber-400",
    initials: "SP",
    actionLabel: "Split PDF",
    faqs: [{ q: "What do I get back?", a: "A .zip archive containing one PDF per page." }],
  },
  {
    slug: "split-by-range",
    name: "Extract Page Range",
    shortDescription: "Pull out a specific range of pages into a new PDF.",
    longDescription: "Specify page numbers or ranges like 1-3,5,8-10 to extract exactly the pages you need into a brand-new PDF file.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-amber-500 to-yellow-400",
    initials: "RG",
    actionLabel: "Extract Range",
    fields: [{ key: "range", label: "Pages to extract", type: "text", placeholder: "e.g. 1-3,5,8-10", defaultValue: "" }],
    faqs: [{ q: "What format should I use?", a: "Comma-separate pages or ranges, e.g. 1-3,5,8-10." }],
  },
  {
    slug: "split-by-size",
    name: "Split by File Size",
    shortDescription: "Break a large PDF into smaller chunks under a target size.",
    longDescription: "Automatically split a big PDF into several smaller files that each stay under your chosen maximum size, delivered as a zip.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-yellow-500 to-lime-400",
    initials: "SZ",
    actionLabel: "Split by Size",
    fields: [{ key: "maxKb", label: "Max size per file (KB)", type: "number", defaultValue: 1024, min: 50 }],
    faqs: [{ q: "How accurate is the size limit?", a: "Each output file is checked against your limit page-by-page, so results are close but not laser-exact." }],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortDescription: "Shrink PDF file size by optimizing page images.",
    longDescription: "Reduce PDF file size by re-encoding every page at an efficient JPEG quality — great for emailing or uploading large documents.",
    category: "Optimize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-lime-500 to-emerald-400",
    initials: "CZ",
    actionLabel: "Compress PDF",
    fields: [
      { key: "quality", label: "Image quality", type: "select", defaultValue: "0.6", options: [
        { label: "Smallest file (lower quality)", value: "0.35" },
        { label: "Balanced (recommended)", value: "0.6" },
        { label: "Best quality (larger file)", value: "0.8" },
      ] },
      { key: "scale", label: "Resolution", type: "select", defaultValue: "1.5", options: [
        { label: "Standard (1.5x)", value: "1.5" },
        { label: "High (2x)", value: "2" },
      ] },
    ],
    faqs: [{ q: "Will text stay selectable?", a: "No — pages are rasterized to shrink size, so the output is image-based. This works best for scanned or image-heavy PDFs." }],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortDescription: "Convert PDF text content into an editable .docx file.",
    longDescription: "Extract the text from every page of your PDF and lay it out into a downloadable Microsoft Word (.docx) document.",
    category: "Convert",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-blue-600 to-sky-400",
    initials: "PW",
    actionLabel: "Convert to Word",
    faqs: [{ q: "Will formatting be preserved?", a: "Text content converts reliably; complex layouts, columns and images are simplified into flowing paragraphs." }],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortDescription: "Convert .docx documents into polished PDFs.",
    longDescription: "Upload a Word (.docx) document and we'll render it to a shareable, print-ready PDF file.",
    category: "Convert",
    inputKind: "docx",
    accept: ".docx",
    color: "from-sky-600 to-cyan-400",
    initials: "WP",
    actionLabel: "Convert to PDF",
    faqs: [{ q: "Which formats are supported?", a: "Modern .docx files. Legacy .doc files should be re-saved as .docx first." }],
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    shortDescription: "Turn each PDF page into a PowerPoint slide.",
    longDescription: "Every page of your PDF becomes a full-bleed image slide inside a downloadable .pptx presentation.",
    category: "Convert",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-red-600 to-orange-500",
    initials: "PP",
    actionLabel: "Convert to PPTX",
    faqs: [{ q: "Can I edit the text afterwards?", a: "Slides are image-based snapshots of each page, so text isn't editable inside PowerPoint." }],
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    shortDescription: "Convert .pptx slide text into a shareable PDF.",
    longDescription: "We read the text content from every slide in your .pptx file and lay it out into a clean, shareable PDF document.",
    category: "Convert",
    inputKind: "pptx",
    accept: ".pptx",
    color: "from-orange-600 to-amber-500",
    initials: "PX",
    actionLabel: "Convert to PDF",
    faqs: [{ q: "Are images and animations kept?", a: "This tool focuses on text content from slides; embedded images, charts and animations aren't rendered." }],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    shortDescription: "Extract PDF text into a structured spreadsheet.",
    longDescription: "Pulls the text from each page of your PDF into rows inside a downloadable .xlsx spreadsheet.",
    category: "Convert",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-green-600 to-emerald-500",
    initials: "PE",
    actionLabel: "Convert to Excel",
    faqs: [{ q: "Does it detect tables?", a: "Text is extracted line by line; complex table grids may need manual cleanup in Excel." }],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    shortDescription: "Convert spreadsheets into print-ready PDF tables.",
    longDescription: "Upload an .xlsx workbook and every sheet is rendered as a formatted table on its own PDF page.",
    category: "Convert",
    inputKind: "xlsx",
    accept: ".xlsx,.xls,.csv",
    color: "from-emerald-600 to-teal-500",
    initials: "EP",
    actionLabel: "Convert to PDF",
    faqs: [{ q: "Are formulas calculated?", a: "Cell values are used as-is; make sure formulas are already calculated in your spreadsheet app before uploading." }],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortDescription: "Export every PDF page as a high-quality JPG image.",
    longDescription: "Render each page of your PDF into a crisp JPG image, downloaded individually or bundled as a zip.",
    category: "Convert",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-fuchsia-600 to-pink-500",
    initials: "PJ",
    actionLabel: "Convert to JPG",
    fields: [{ key: "scale", label: "Image resolution", type: "select", defaultValue: "2", options: [
      { label: "Standard (1.5x)", value: "1.5" },
      { label: "High (2x)", value: "2" },
      { label: "Ultra (3x)", value: "3" },
    ] }],
    faqs: [{ q: "What if my PDF has many pages?", a: "You'll get a zip file containing one JPG per page." }],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortDescription: "Combine JPG photos into a single PDF document.",
    longDescription: "Select one or more JPG images and we'll lay each one on its own page inside a new PDF.",
    category: "Convert",
    inputKind: "images",
    accept: "image/jpeg",
    multiple: true,
    color: "from-pink-600 to-rose-500",
    initials: "JP",
    actionLabel: "Convert to PDF",
    fields: [{ key: "margin", label: "Page margin (pt)", type: "number", defaultValue: 24, min: 0 }],
    faqs: [{ q: "Can I reorder images?", a: "Yes, drag images in the upload list before converting." }],
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    shortDescription: "Export PDF pages as transparent-ready PNG images.",
    longDescription: "Render each page of your PDF as a lossless PNG image, ideal for graphics that need sharp edges or transparency.",
    category: "Convert",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-violet-600 to-purple-500",
    initials: "PN",
    actionLabel: "Convert to PNG",
    fields: [{ key: "scale", label: "Image resolution", type: "select", defaultValue: "2", options: [
      { label: "Standard (1.5x)", value: "1.5" },
      { label: "High (2x)", value: "2" },
      { label: "Ultra (3x)", value: "3" },
    ] }],
    faqs: [{ q: "PNG vs JPG — which should I choose?", a: "PNG keeps sharper lines and text; JPG files are usually smaller for photos." }],
  },
  {
    slug: "png-to-pdf",
    name: "PNG to PDF",
    shortDescription: "Combine PNG images into a single PDF document.",
    longDescription: "Select one or more PNG images and we'll lay each one on its own page inside a new PDF.",
    category: "Convert",
    inputKind: "images",
    accept: "image/png",
    multiple: true,
    color: "from-purple-600 to-indigo-500",
    initials: "NP",
    actionLabel: "Convert to PDF",
    fields: [{ key: "margin", label: "Page margin (pt)", type: "number", defaultValue: 24, min: 0 }],
    faqs: [{ q: "Does transparency matter?", a: "Transparent areas are flattened to white in the final PDF page." }],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    shortDescription: "Add text annotations straight onto any PDF page.",
    longDescription: "Drop in custom text anywhere on a chosen page — perfect for quick notes, labels or corrections.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-indigo-600 to-blue-500",
    initials: "ED",
    actionLabel: "Add Text",
    fields: [
      { key: "text", label: "Text to add", type: "text", placeholder: "Your note…" },
      { key: "page", label: "Page number", type: "number", defaultValue: 1, min: 1 },
      { key: "x", label: "X position (pt from left)", type: "number", defaultValue: 50 },
      { key: "y", label: "Y position (pt from bottom)", type: "number", defaultValue: 50 },
      { key: "size", label: "Font size", type: "number", defaultValue: 18, min: 6, max: 96 },
      { key: "color", label: "Text color", type: "color", defaultValue: "#111827" },
    ],
    faqs: [{ q: "Can I add text to multiple pages?", a: "Run the tool again for each page you'd like to annotate." }],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    shortDescription: "Draw your signature and place it onto a PDF page.",
    longDescription: "Draw a signature with your mouse or finger, then stamp it anywhere on any page of your PDF.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-blue-600 to-indigo-500",
    initials: "SG",
    actionLabel: "Sign PDF",
    fields: [
      { key: "page", label: "Page number", type: "number", defaultValue: 1, min: 1 },
      { key: "x", label: "X position (pt from left)", type: "number", defaultValue: 60 },
      { key: "y", label: "Y position (pt from bottom)", type: "number", defaultValue: 60 },
      { key: "width", label: "Signature width (pt)", type: "number", defaultValue: 160, min: 40, max: 400 },
    ],
    faqs: [{ q: "Is my signature stored anywhere?", a: "No — it's drawn in your browser and embedded directly into the downloaded PDF only." }],
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    shortDescription: "Stamp a custom text watermark across every page.",
    longDescription: "Add a diagonal (or straight) semi-transparent text watermark across every page of your PDF — great for drafts and branding.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-teal-600 to-cyan-500",
    initials: "WM",
    actionLabel: "Add Watermark",
    fields: [
      { key: "text", label: "Watermark text", type: "text", defaultValue: "CONFIDENTIAL" },
      { key: "opacity", label: "Opacity", type: "number", defaultValue: 0.25, min: 0.05, max: 1 },
      { key: "fontSize", label: "Font size", type: "number", defaultValue: 60, min: 10, max: 200 },
      { key: "rotation", label: "Rotation (deg)", type: "number", defaultValue: 45, min: 0, max: 360 },
      { key: "color", label: "Color", type: "color", defaultValue: "#ef4444" },
    ],
    faqs: [{ q: "Can I remove it later?", a: "The watermark is merged into the page content, so it can't be auto-removed afterwards." }],
  },
  {
    slug: "add-stamp",
    name: "Add Stamp / Logo",
    shortDescription: "Place an image stamp or logo on every page.",
    longDescription: "Upload a small logo or stamp image and position it in a corner of every page in your PDF.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-cyan-600 to-sky-500",
    initials: "ST",
    actionLabel: "Add Stamp",
    fields: [
      { key: "position", label: "Position", type: "select", defaultValue: "bottom-right", options: [
        { label: "Top left", value: "top-left" }, { label: "Top right", value: "top-right" },
        { label: "Bottom left", value: "bottom-left" }, { label: "Bottom right", value: "bottom-right" },
        { label: "Center", value: "center-middle" },
      ] },
      { key: "width", label: "Stamp width (pt)", type: "number", defaultValue: 90, min: 20, max: 400 },
    ],
    faqs: [{ q: "Which image formats work?", a: "JPG and PNG logos are supported." }],
  },
  {
    slug: "header-footer",
    name: "Header & Footer",
    shortDescription: "Add a repeating header and/or footer line to every page.",
    longDescription: "Insert custom header and footer text that repeats consistently across every page of your document.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-sky-600 to-blue-500",
    initials: "HF",
    actionLabel: "Add Header & Footer",
    fields: [
      { key: "header", label: "Header text", type: "text", placeholder: "e.g. Company Confidential" },
      { key: "footer", label: "Footer text", type: "text", placeholder: "e.g. © 2026 Your Company" },
    ],
    faqs: [{ q: "Can I include page numbers here too?", a: "Use the dedicated Page Numbers tool for automatic numbering." }],
  },
  {
    slug: "page-numbers",
    name: "Page Numbers",
    shortDescription: "Automatically number every page of your PDF.",
    longDescription: "Add clean, consistent page numbers in the position and format you choose, across every page.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-blue-600 to-violet-500",
    initials: "PN",
    actionLabel: "Add Page Numbers",
    fields: [
      { key: "position", label: "Position", type: "select", defaultValue: "bottom-center", options: [
        { label: "Bottom center", value: "bottom-center" }, { label: "Bottom left", value: "bottom-left" },
        { label: "Bottom right", value: "bottom-right" }, { label: "Top center", value: "top-center" },
      ] },
      { key: "startAt", label: "Start numbering at", type: "number", defaultValue: 1, min: 1 },
      { key: "format", label: "Format", type: "text", defaultValue: "Page {n} of {total}", help: "Use {n} and {total} placeholders." },
    ],
    faqs: [{ q: "Can I skip the cover page?", a: "Use the Split tool to remove the cover page first, number the rest, then merge them back." }],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortDescription: "Rotate every page (or a range) by 90°, 180° or 270°.",
    longDescription: "Fix sideways or upside-down scans by rotating all or some pages of your PDF.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-violet-600 to-fuchsia-500",
    initials: "RT",
    actionLabel: "Rotate PDF",
    fields: [
      { key: "angle", label: "Rotate by", type: "select", defaultValue: "90", options: [
        { label: "90° clockwise", value: "90" }, { label: "180°", value: "180" }, { label: "270° clockwise", value: "270" },
      ] },
      { key: "range", label: "Pages (blank = all)", type: "text", placeholder: "e.g. 1,3-5" },
    ],
    faqs: [{ q: "Can I rotate just one page?", a: "Yes, enter that page number in the pages field." }],
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    shortDescription: "Delete unwanted pages from a PDF.",
    longDescription: "Specify the pages you no longer need and download a new PDF with them removed.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-red-600 to-rose-500",
    initials: "RM",
    actionLabel: "Remove Pages",
    fields: [{ key: "range", label: "Pages to remove", type: "text", placeholder: "e.g. 2,4-5" }],
    faqs: [{ q: "Can I undo this?", a: "Keep your original file — removal happens on a fresh copy, downloaded separately." }],
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    shortDescription: "Pull specific pages out into their own PDF.",
    longDescription: "Choose exactly which pages to keep and we'll build a brand-new PDF from just those pages.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-rose-600 to-pink-500",
    initials: "EX",
    actionLabel: "Extract Pages",
    fields: [{ key: "range", label: "Pages to extract", type: "text", placeholder: "e.g. 1-3,5" }],
    faqs: [{ q: "How is this different from Split?", a: "Split breaks a PDF into many files; this tool extracts your chosen pages into a single new PDF." }],
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    shortDescription: "Reorder pages into any custom sequence.",
    longDescription: "Type the new page order you'd like (e.g. 3,1,2,4) and we'll rebuild your PDF in that exact sequence.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-pink-600 to-fuchsia-500",
    initials: "OG",
    actionLabel: "Organize PDF",
    fields: [{ key: "order", label: "New page order", type: "text", placeholder: "e.g. 3,1,2,4" }],
    faqs: [{ q: "Do I need to list every page?", a: "Yes, include every page number exactly once in your desired order." }],
  },
  {
    slug: "reverse-pages",
    name: "Reverse Pages",
    shortDescription: "Flip the order of every page in a PDF.",
    longDescription: "Instantly reverse your document so the last page becomes the first.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-fuchsia-600 to-purple-500",
    initials: "RV",
    actionLabel: "Reverse Pages",
    faqs: [{ q: "Does this affect page numbers printed on the page?", a: "No, only page order changes — any printed numbers stay as they were." }],
  },
  {
    slug: "duplicate-pages",
    name: "Duplicate Pages",
    shortDescription: "Insert a copy right after chosen pages.",
    longDescription: "Duplicate specific pages (or every page) immediately after their original, useful for templates and inserts.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-purple-600 to-violet-500",
    initials: "DP",
    actionLabel: "Duplicate Pages",
    fields: [{ key: "range", label: "Pages to duplicate (blank = all)", type: "text", placeholder: "e.g. 1,3" }],
    faqs: [{ q: "Where is the duplicate placed?", a: "Immediately after the original page." }],
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    shortDescription: "Trim margins from every page of a PDF.",
    longDescription: "Set custom top, bottom, left and right margins to crop away unwanted white space or content.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-gray-600 to-slate-500",
    initials: "CR",
    actionLabel: "Crop PDF",
    fields: [
      { key: "top", label: "Top margin (pt)", type: "number", defaultValue: 20, min: 0 },
      { key: "right", label: "Right margin (pt)", type: "number", defaultValue: 20, min: 0 },
      { key: "bottom", label: "Bottom margin (pt)", type: "number", defaultValue: 20, min: 0 },
      { key: "left", label: "Left margin (pt)", type: "number", defaultValue: 20, min: 0 },
    ],
    faqs: [{ q: "Is cropping reversible?", a: "Cropping only changes the visible crop box; keep your original file to go back to full page size." }],
  },
  {
    slug: "nup-pdf",
    name: "Multiple Pages per Sheet",
    shortDescription: "Combine 2 or 4 pages onto a single sheet.",
    longDescription: "Great for handouts — lay out 2 or 4 original pages onto each new A4 sheet.",
    category: "Organize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-stone-600 to-neutral-500",
    initials: "NU",
    actionLabel: "Combine Pages",
    fields: [{ key: "n", label: "Pages per sheet", type: "select", defaultValue: "2", options: [
      { label: "2 per sheet", value: "2" }, { label: "4 per sheet", value: "4" },
    ] }],
    faqs: [{ q: "What page size is used for the output?", a: "A4 — pages are scaled proportionally to fit." }],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    shortDescription: "Lock your PDF behind a password with real encryption.",
    longDescription: "Add genuine, industry-standard 128-bit password encryption so only people with the password can open your PDF.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-emerald-600 to-green-500",
    initials: "PT",
    actionLabel: "Protect PDF",
    fields: [
      { key: "userPassword", label: "Password required to open", type: "password" },
      { key: "ownerPassword", label: "Owner password (optional)", type: "password" },
      { key: "printing", label: "Allow printing", type: "checkbox", defaultValue: true },
      { key: "copying", label: "Allow copying text", type: "checkbox", defaultValue: true },
      { key: "modifying", label: "Allow editing", type: "checkbox", defaultValue: false },
      { key: "annotating", label: "Allow annotations", type: "checkbox", defaultValue: true },
    ],
    faqs: [{ q: "What encryption is used?", a: "Standard PDF encryption (RC4, 128-bit, revision 3) — supported by virtually every PDF reader." }],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    shortDescription: "Remove password protection when you know the password.",
    longDescription: "Enter the current password to produce a brand-new, unprotected copy of your PDF.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-green-600 to-lime-500",
    initials: "UL",
    actionLabel: "Unlock PDF",
    fields: [{ key: "password", label: "Current password", type: "password" }],
    faqs: [{ q: "Does this crack unknown passwords?", a: "No — you must know the correct password. This tool only removes protection, it doesn't bypass security." }],
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    shortDescription: "Permanently black out sensitive page areas.",
    longDescription: "Draw black boxes over sensitive content; the page is rebuilt as a flattened image so the hidden content can't be recovered.",
    category: "Edit & Secure",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-neutral-800 to-zinc-600",
    initials: "RD",
    actionLabel: "Redact & Flatten",
    faqs: [{ q: "Is redacted text really unrecoverable?", a: "Yes — the output page is a flattened image, so there's no underlying text layer left to extract." }],
  },
  {
    slug: "grayscale-pdf",
    name: "Grayscale PDF",
    shortDescription: "Convert a colorful PDF into black & white.",
    longDescription: "Strip the color out of every page — ideal for cheaper printing or a more formal look.",
    category: "Optimize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-zinc-600 to-gray-500",
    initials: "GS",
    actionLabel: "Convert to Grayscale",
    faqs: [{ q: "Will this also reduce file size?", a: "Often yes, since grayscale JPEGs compress a bit more efficiently than color ones." }],
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    shortDescription: "Attempt to fix a corrupted or broken PDF file.",
    longDescription: "Re-parses and rebuilds a damaged PDF's internal structure, falling back to a page-by-page rebuild if needed.",
    category: "Optimize",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-amber-700 to-orange-600",
    initials: "RP",
    actionLabel: "Repair PDF",
    faqs: [{ q: "Can every corrupted PDF be fixed?", a: "Not always — severely damaged files may only be partially recoverable." }],
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    shortDescription: "Spot text differences between two PDF files.",
    longDescription: "Upload two PDFs and get a page-by-page report highlighting exactly which pages differ.",
    category: "Utilities",
    inputKind: "two-pdf",
    accept: "application/pdf",
    color: "from-blue-700 to-indigo-600",
    initials: "CP",
    actionLabel: "Compare PDFs",
    faqs: [{ q: "Does this compare images too?", a: "No, comparison is based on extracted text content only." }],
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    shortDescription: "Convert raw HTML markup into a formatted PDF.",
    longDescription: "Paste any HTML snippet and instantly render it into a downloadable PDF document.",
    category: "Convert",
    inputKind: "html",
    accept: "",
    color: "from-indigo-700 to-blue-600",
    initials: "HP",
    actionLabel: "Convert to PDF",
    fields: [{ key: "html", label: "HTML content", type: "textarea", placeholder: "<h1>Hello world</h1><p>Your content here…</p>" }],
    faqs: [{ q: "Are external stylesheets supported?", a: "Inline styles work best; external CSS files aren't fetched." }],
  },
  {
    slug: "extract-text",
    name: "Extract Text",
    shortDescription: "Pull all readable text out of a PDF.",
    longDescription: "Extracts every page's text content into a plain .txt file you can copy, search or repurpose.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-teal-700 to-emerald-600",
    initials: "ET",
    actionLabel: "Extract Text",
    faqs: [{ q: "What about scanned PDFs?", a: "Scanned pages have no embedded text — use the OCR PDF tool for those instead." }],
  },
  {
    slug: "extract-images",
    name: "Extract Images",
    shortDescription: "Save each PDF page as a standalone image.",
    longDescription: "Renders every page as a high-resolution PNG so you can reuse visuals from your PDF.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-cyan-700 to-teal-600",
    initials: "EI",
    actionLabel: "Extract Images",
    fields: [{ key: "scale", label: "Resolution", type: "select", defaultValue: "2", options: [
      { label: "Standard (1.5x)", value: "1.5" }, { label: "High (2x)", value: "2" }, { label: "Ultra (3x)", value: "3" },
    ] }],
    faqs: [{ q: "Does this extract embedded photos only?", a: "It captures each full page as an image, which includes any photos, graphics and text on that page." }],
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    shortDescription: "Recognize and extract text from scanned PDFs.",
    longDescription: "Runs optical character recognition directly in your browser to pull text out of scanned or image-only PDFs.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-rose-700 to-pink-600",
    initials: "OC",
    actionLabel: "Run OCR",
    faqs: [{ q: "How long does OCR take?", a: "It runs fully on-device, so larger or multi-page scans can take a little longer depending on your computer." }],
  },
  {
    slug: "pdf-metadata",
    name: "Edit PDF Metadata",
    shortDescription: "Update a PDF's title, author, subject and keywords.",
    longDescription: "Change the document properties embedded in your PDF — handy for organizing and cataloging files.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-lime-700 to-green-600",
    initials: "MD",
    actionLabel: "Update Metadata",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "author", label: "Author", type: "text" },
      { key: "subject", label: "Subject", type: "text" },
      { key: "keywords", label: "Keywords (comma separated)", type: "text" },
    ],
    faqs: [{ q: "Will this change visible page content?", a: "No, only the hidden document properties are changed." }],
  },
  {
    slug: "fill-flatten-form",
    name: "Flatten PDF Form",
    shortDescription: "Lock in form field values so they can't be edited.",
    longDescription: "Flattens any fillable form fields in your PDF into permanent, non-editable page content.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    color: "from-yellow-700 to-amber-600",
    initials: "FF",
    actionLabel: "Flatten Form",
    faqs: [{ q: "What if my PDF has no form fields?", a: "You'll see a friendly message explaining there's nothing to flatten." }],
  },
  {
    slug: "pdf-analyzer",
    name: "PDF Info & Analyzer",
    shortDescription: "Inspect page count, size, and document metadata.",
    longDescription: "Quickly check page count, file size, PDF version and embedded metadata without opening another app.",
    category: "Utilities",
    inputKind: "single-pdf",
    accept: "application/pdf",
    needsPassword: true,
    color: "from-orange-700 to-red-600",
    initials: "IA",
    actionLabel: "Analyze PDF",
    faqs: [{ q: "Does this modify my file?", a: "No, this tool is read-only — nothing is changed or uploaded anywhere." }],
  },
];

export function getToolBySlug(slug: string): ToolDef | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: Category): ToolDef[] {
  return tools.filter((t) => t.category === category);
}

export function getRelatedTools(tool: ToolDef, count = 4): ToolDef[] {
  return tools.filter((t) => t.category === tool.category && t.slug !== tool.slug).slice(0, count);
}
